name: Android APK CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

#  ✅  Rename the helper var so Buildozer won’t treat it as a token override
env:
  APP_SUBDIR: app

jobs:
  build-android:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      # ---- Build the APK ----
      - name: Build APK with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          #  ✅  Run Buildozer from the repo *root* where buildozer.spec lives
          workdir: .
          #     (If you moved the spec into app/, set workdir: ${{ env.APP_SUBDIR }})
          buildozer_version: stable
          log_level: 2

      # ---- Publish artifact ----
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: faceapp-apk
          path: ${{ steps.buildozer.outputs.filename }}
